//
//  TestData.swift
//  Disclosure
//
//  Created by Tyson Freeze on 3/2/24.
//

import Foundation

struct TestData {
    static let myTeam: [Person] = [
        Person(name: "Ippo Makunouchi", relation: Relation.sponsor, phone: "11231231234", checkInDate: Date.from(year: 2024, month: 2, day: 3)),
        Person(name: "Barbie Doll", relation: Relation.group, phone: "11231231234"),
        Person(name: "Ken Doll", relation: Relation.group, phone: "11231231234"),
        Person(name: "Mom", relation: Relation.other, phone: "11231231234", checkInDate: Date.from(year: 2024, month: 3, day: 1)),
        Person(name: "Sister", relation: Relation.other, phone: "11231231234"),
        Person(name: "Father-in-Law", relation: Relation.other, phone: "11231231234", checkInDate: Date.from(year: 2023, month: 3, day: 2))
    ]
    
    static let spreadsheet: [Relapse] = [
        Relapse(date: Date.from(year: 2024, month: 3, day: 2), reminder: true, intensity: 5, compulsivity: 3, notes: "I was a little hungry, just finished taxes. Low compulsion, I just wanted to more than I didn’t. (TikTok)", triggers: ["Bored", "Hunger"]),
        Relapse(date: Date.from(year: 2024, month: 3, day: 2), intensity: 7, compulsivity: 5, notes: "I had eaten. Just shame I think.", triggers: ["Anger"]),
        //February
        Relapse(date: Date.from(year: 2024, month: 2, day: 3), intensity: 2, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 5), intensity: 6, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 5), intensity: 8, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 10), intensity: 2, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 17), intensity: 4, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 20), intensity: 2, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 26), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 26), intensity: 8, compulsivity: Int.random(in: 1...10)),
        //Etc...
        Relapse(date: Date.from(year: 2024, month: 1, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 17), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 17), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 20), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 12), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 5), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 1), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 21), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 31), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 2), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 20), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 21), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 1), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 2), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 21), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 12), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 24), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 31), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 2), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 20), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 28), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 5), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 12), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 1), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10))
    ]
    
    static let october: [Relapse] = [
        Relapse(date: Date.from(year: 2023, month: 10, day: 6), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 6), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 7), intensity: 1, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 11), intensity: 1, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 17), intensity: 1, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 20), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 26), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 26), intensity: 10, compulsivity: Int.random(in: 1...10))
    ]
}
