//
//  TestData.swift
//  Disclosure
//
//  Created by Tyson Freeze on 3/2/24.
//

import Foundation

struct TestData {
    static let journal: [Entry] = [
        Entry(isGoal: true, title: "I need to", body: "Go to sleep\nAnd stop “screening” my needs", date: Date.from(year: 2023, month: 12, day: 11)),
        Entry(isGoal: false, title: "'I know what I need you to do. Just trust me and go along with it ❤️' - God", body: "In fast and testimony meeting 3/3/24", date: Date.from(year: 2024, month: 3, day: 3)),
        Entry(isGoal: true, title: "The Plan:", body: "Alma 22:18\n“I will give away all my sins to know thee”\n\nB\nL\nA\nS ⭐️\nT ⭐️ (no safari on phone)\nH ⭐️\nO\n- feeling stuck\n- Slacking at work (escape patterns) ⭐️⭐️⭐️ (figure this out next)\n- Overwhelm (exhaustion)\n\nStudy Christ’s saving power\n\nWww.anxietycoach.com\nSelf help stuff\nGlance through the anxiety disorders", date: Date.from(year: 2023, month: 10, day: 10)),
        Entry(isGoal: false, title: "Fun is Need Realization", body: "Why do I slack off at work?\n- hate my job\n- Tired\n- Hungry\n\nI think my real problem is having fun. What most other people like to do isn’t fun for me. Whitney works more. \n\nFun:\n- Playfulness\n- Connection\n- Flow\n\nFun Factors:\n- Outdoors\n- Anticipation\n- Small groups\n- Learning/trying new things\n- Fandoms\n- Food\n\nFun Times:\n- Riding horses with Whitney\n- First birthday with Whitney\n- Camping\n- Rock climbing \n- National Parks\n- Cheesecake Dates with myself\n- Playmill Theater with Whitney\n- Mesa Falls\n- Indiana Jones Movie\n- Biking with Amber in the Rain and Mud to Raising Cane’s. \n- Going to Conference with Whitney and getting Raising Cane’s. Talking the whole way home. \n", date: Date.from(year: 2023, month: 11, day: 2))
    ]
    
    static let myTeam: [Person] = [
        Person(name: "Ippo Makunouchi", relation: Relation.sponsor, phone: "11231231234", latestCall: Date.from(year: 2024, month: 2, day: 3), canText: true),
        Person(name: "Barbie Doll", relation: Relation.group, phone: "11231231234"),
        Person(name: "Ken Doll", relation: Relation.group, phone: "11231231234"),
        Person(name: "Mom", relation: Relation.other, phone: "11231231234", latestCall: Date.from(year: 2024, month: 3, day: 1)),
        Person(name: "Sister", relation: Relation.other, phone: "11231231234", canText: true),
        Person(name: "Father-in-Law", relation: Relation.other, phone: "11231231234", latestCall: Date.from(year: 2023, month: 3, day: 2), canText: true)
    ]
    
    static let spreadsheet: [Relapse] = [
        Relapse(date: Date.from(year: 2024, month: 3, day: 13), intensity: 1, compulsivity: 4, notes: "I think I was just tired, 7 or 6 hours instead of the ideal 9. Low shame, just got to keep moving forward. Chances are good Mar will be much better than Feb.", triggers: ["Tiredness", "Hunger"]),
        Relapse(date: Date.from(year: 2024, month: 3, day: 2), reminder: true, intensity: 5, compulsivity: 3, notes: "I was a little hungry, just finished taxes. Low compulsion, I just wanted to more than I didn’t. (TikTok)", triggers: ["Bored", "Hunger"]),
        Relapse(date: Date.from(year: 2024, month: 3, day: 2), intensity: 7, compulsivity: 5, notes: "I had eaten. Just shame I think.", triggers: ["Anger"]),
        //February
        Relapse(date: Date.from(year: 2024, month: 2, day: 3), intensity: 2, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 5), intensity: 6, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 5), intensity: 8, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 10), intensity: 2, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 17), intensity: 4, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 20), intensity: 2, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 26), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 26), intensity: 8, compulsivity: Int.random(in: 1...10)),
        //Etc...
        Relapse(date: Date.from(year: 2024, month: 1, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 17), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 17), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 20), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 12), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 5), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 1), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 21), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 5, day: 31), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 2), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 20), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 21), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 4, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 1), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 2), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 21), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 3, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 12), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 22), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 2, day: 24), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 19), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 1, day: 31), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 2), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 6), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 16), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 20), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 12, day: 28), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 5), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 10), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 12), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 13), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 11, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 1), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 7), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 8), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 11), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 25), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 10, day: 26), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 14), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 15), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 23), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 29), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 9, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 3), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 4), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 9), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 18), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 27), intensity: 5, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2022, month: 8, day: 30), intensity: 5, compulsivity: Int.random(in: 1...10))
    ]
    
    static let october: [Relapse] = [
        Relapse(date: Date.from(year: 2023, month: 10, day: 6), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 6), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 7), intensity: 1, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 11), intensity: 1, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 17), intensity: 1, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 20), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 26), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 26), intensity: 10, compulsivity: Int.random(in: 1...10))
    ]
}
