//
//  TestData.swift
//  Disclosure
//
//  Created by Tyson Freeze on 3/2/24.
//

import Foundation

struct TestData {
    
    static let journal: [Entry] = [
    ]
    
    static let myTeam: [Person] = [
        Person(name: "Jackson Miller", relation: Relation.sponsor, phone: "", latestCall: Date.from(year: 2024, month: 12, day: 10), canText: true),
        Person(name: "Ethan", relation: Relation.group, phone: "", latestCall: Date.from(year: 2024, month: 12, day: 8), canText: true),
        Person(name: "Landon", relation: Relation.group, phone: "", latestCall: Date.from(year: 2024, month: 12, day: 6)),
        Person(name: "Caleb", relation: Relation.group, phone: "", latestCall: Date.from(year: 2024, month: 12, day: 6), canText: true),
        Person(name: "Mason", relation: Relation.group, phone: ""),
        Person(name: "Garrett", relation: Relation.group, phone: "", canText: true),
        Person(name: "Mom", relation: Relation.other, phone: "", latestCall: Date.from(year: 2024, month: 11, day: 20), canText: true),
        Person(name: "Sister", relation: Relation.other, phone: ""),
        Person(name: "Wife", relation: Relation.other, phone: "", latestCall: Date.from(year: 2024, month: 12, day: 10), canText: true)
    ]
    
    static let spreadsheet: [Relapse] = [
        Relapse(date: Date.from(year: 2024, month: 10, day: 26), intensity: 10, compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 10, day: 26), intensity: 8, compulsivity: Int.random(in: 1...10)),
        //Etc...
        Relapse(date: Date.from(year: 2024, month: 10, day: 10), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 10, day: 18), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 10, day: 26), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 10, day: 6), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 10, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 10, day: 13), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 9, day: 3), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 9, day: 7), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 9, day: 14), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 9, day: 16), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 9, day: 17), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 9, day: 30), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 8, day: 6), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 8, day: 7), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 8, day: 11), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 8, day: 17), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 8, day: 20), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 8, day: 26), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 7, day: 4), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 7, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 7, day: 12), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 7, day: 15), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 7, day: 22), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 7, day: 29), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 6, day: 7), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 6, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 6, day: 11), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 6, day: 23), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 6, day: 26), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 5, day: 8), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 5, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 5, day: 11), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 5, day: 15), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 5, day: 19), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 3), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 5), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 13), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 14), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 22), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 23), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 25), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 26), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 4, day: 30), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 1), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 8), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 10), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 16), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 19), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 21), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 25), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 29), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 3, day: 31), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 2), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 3), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 7), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 15), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 19), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 20), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 21), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 26), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 27), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 2, day: 29), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 1), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 2), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 16), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 21), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 22), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2024, month: 1, day: 27), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 4), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 8), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 10), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 12), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 16), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 22), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 23), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 12, day: 24), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 6), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 11), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 16), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 19), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 23), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 25), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 27), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 11, day: 31), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 2), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 3), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 6), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 13), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 16), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 18), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 20), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 23), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 10, day: 28), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 4), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 5), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 8), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 10), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 12), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 13), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 18), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 9, day: 25), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 1), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 7), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 8), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 11), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 14), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 18), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 25), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 8, day: 26), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 4), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 14), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 15), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 23), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 29), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 7, day: 30), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 3), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 4), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 9), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 18), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 27), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10)),
        Relapse(date: Date.from(year: 2023, month: 6, day: 30), intensity: Int.random(in: 1...10), compulsivity: Int.random(in: 1...10))
    ]
}
